Repository boostcampwm-2024/iOS01-Ret-s-Talk, pull requests merged in 2024-12, with the labels that each got.

#162 회고 캘린더 뷰 구성
  RetsTalk/RetsTalk/Retrospect/Model/MockRetrospectManager.swift
  RetsTalk/RetsTalk/RetrospectCalendar/Controller/RetrospectCalendarViewController.swift
  RetsTalk/RetsTalk/RetrospectCalendar/View/RetrospectCalendarView.swift
  RetsTalk/RetsTalk/Utility/Extensions/Date+Extension.swift
Labels: 💡 Feature

#145 알림기능: 인터페이스, 구현체, 기능 연결
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/User/Controller/UserSettingViewController.swift
  RetsTalk/RetsTalk/User/Model/NotificationManageable.swift
  RetsTalk/RetsTalk/User/Model/NotificationManager.swift
  RetsTalk/RetsTalk/User/Model/UserSettingManageable.swift
  RetsTalk/RetsTalk/User/Model/UserSettingManager.swift
  RetsTalk/RetsTalk/User/Subview/AppVersionView.swift
  RetsTalk/RetsTalk/User/Subview/CloudSettingView.swift
  RetsTalk/RetsTalk/User/Subview/NicknameModalView.swift
  RetsTalk/RetsTalk/User/Subview/NicknameSettingView.swift
  RetsTalk/RetsTalk/User/Subview/NotificationSettingView.swift
  RetsTalk/RetsTalk/User/UserSettingView.swift
Labels: 💡 Feature

#154 UserSettingManager: 사용자 ID 반환/부여하는 기능
  RetsTalk/RetsTalk/User/Model/UserData.swift
  RetsTalk/RetsTalk/User/Model/UserSettingManageable.swift
  RetsTalk/RetsTalk/User/Model/UserSettingManager.swift
Labels: 💡 Feature

#165 사용자 설정 화면: 충돌 해소 및 수반되는 오류 해결
  RetsTalk/RetsTalk/User/Model/NotificationManageable.swift
  RetsTalk/RetsTalk/User/Model/NotificationManager.swift
  RetsTalk/RetsTalk/User/Model/UserSettingManageable.swift
  RetsTalk/RetsTalk/User/Model/UserSettingManager.swift
  RetsTalk/RetsTalk/User/Subview/NicknameModalView.swift
  RetsTalk/RetsTalk/User/Subview/NicknameSettingView.swift
  RetsTalk/RetsTalk/User/Subview/NotificationSettingView.swift
  RetsTalk/RetsTalk/User/UserSettingView.swift
Labels: 🛠️ Fix

#167 회고 캘린더에서 날짜 클릭시 데이터를 들고오도록 구현
  RetsTalk/RetsTalk/Retrospect/Model/MockRetrospectManager.swift
  RetsTalk/RetsTalk/RetrospectCalendar/Controller/RetrospectCalendarViewController.swift
  RetsTalk/RetsTalk/RetrospectCalendar/View/RetrospectCalendarView.swift
Labels: 💡 Feature

#173 회고목록 달력 버튼 UI: 회고 쓴 일수, 총 회고 수
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Retrospect/View/RetrospectCountButton.swift
  RetsTalk/RetsTalk/Retrospect/View/RetrospectListView.swift
  RetsTalk/RetsTalk/Utility/Enums/FontSet.swift
Labels: 💡 Feature

#183 달력 버튼 레이아웃, 터치영역 수정
  RetsTalk/RetsTalk/Retrospect/View/RetrospectCountButton.swift
  RetsTalk/RetsTalk/Retrospect/View/RetrospectListView.swift
Labels: 🛠️ Fix, 🎨 Style

#182 회고목록 테이블뷰: DiffableDatasource 리팩토링
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/SortedRetrospects.swift
  RetsTalk/RetsTalk/Retrospect/View/RetrospectListView.swift
  RetsTalk/RetsTalk/Retrospect/View/SectionHeaderView.swift
  RetsTalk/RetsTalk/Utility/RetrospectSortingHelper.swift
Labels: 💪 Refactor

#180 Persistent, Network 영역에 격리를 없애고 각 부분에 맞는 격리로 되도록 개선
  RetsTalk/RetsTalk/Chat/Model/AssistantMessageProvider.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManagerListener.swift
  RetsTalk/RetsTalk/Network/CLOVAStudio/CLOVAStudioManager.swift
  RetsTalk/RetsTalk/Network/NetworkRequestable.swift
  RetsTalk/RetsTalk/Persistent/Implementation/CoreDataManager.swift
  RetsTalk/RetsTalk/Persistent/Implementation/UserDefaultsManager.swift
  RetsTalk/RetsTalk/Persistent/Persistable.swift
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalk/Retrospect/Model/SummaryProvider.swift
  RetsTalk/RetsTalk/User/Model/UserSettingManager.swift
Labels: 💪 Refactor

#185 베이스에 맞게 회고 대화 화면 리팩터링(#130)
  RetsTalk/RetsTalk/Chat/Controller/RetrospectChatViewController.swift
  RetsTalk/RetsTalk/Chat/View/ChatView.swift
  RetsTalk/RetsTalk/Chat/View/MessageInputView.swift
  RetsTalk/RetsTalk/Retrospect/Model/MockRetrospectManager.swift
Labels: 💪 Refactor

#189 UserSettingManager 내부에 NotificationManager가 있도록 수정, 권한 없을 때 알림 요청 시 이상 동작하는 버그 수정
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Chat/Controller/RetrospectChatViewController.swift
  RetsTalk/RetsTalk/Chat/Model/AssistantMessageProvider.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManagerListener.swift
  RetsTalk/RetsTalk/Chat/View/ChatView.swift
  RetsTalk/RetsTalk/Chat/View/MessageInputView.swift
  RetsTalk/RetsTalk/Network/CLOVAStudio/CLOVAStudioManager.swift
  RetsTalk/RetsTalk/Network/NetworkRequestable.swift
  RetsTalk/RetsTalk/Persistent/Implementation/CoreDataManager.swift
  RetsTalk/RetsTalk/Persistent/Implementation/UserDefaultsManager.swift
  RetsTalk/RetsTalk/Persistent/Persistable.swift
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/MockRetrospectManager.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalk/Retrospect/Model/SortedRetrospects.swift
  RetsTalk/RetsTalk/Retrospect/Model/SummaryProvider.swift
  RetsTalk/RetsTalk/Retrospect/View/RetrospectCountButton.swift
  RetsTalk/RetsTalk/Retrospect/View/RetrospectListView.swift
  RetsTalk/RetsTalk/Retrospect/View/SectionHeaderView.swift
  RetsTalk/RetsTalk/User/Controller/UserSettingViewController.swift
  RetsTalk/RetsTalk/User/Model/NotificationManager.swift
  RetsTalk/RetsTalk/User/Model/UserSettingManageable.swift
  RetsTalk/RetsTalk/User/Model/UserSettingManager.swift
  RetsTalk/RetsTalk/User/UserSettingView.swift
  RetsTalk/RetsTalk/Utility/RetrospectSortingHelper.swift
  RetsTalk/RetsTalk/Utility/View/AlertPresentable.swift
  RetsTalk/RetsTalk/Utility/View/BaseHostingViewController.swift
  RetsTalk/RetsTalk/Utility/View/BaseKeyBoardViewController.swift
  RetsTalk/RetsTalk/Utility/View/BaseView.swift
  RetsTalk/RetsTalk/Utility/View/BaseViewController.swift
  RetsTalk/RetsTalk/Utility/View/KeyboardInfo.swift
Labels: 🛠️ Fix, 💪 Refactor

#184 달력 View에서 달력, 회고 목록 ViewController 분리, Modal로 캘린더 뷰 띄우도록 구성
  RetsTalk/RetsTalk/RetrospectCalendar/Controller/RetrospectCalendarTableViewController.swift
  RetsTalk/RetsTalk/RetrospectCalendar/Controller/RetrospectCalendarViewController.swift
  RetsTalk/RetsTalk/RetrospectCalendar/View/RetrospectCalendarTableView.swift
  RetsTalk/RetsTalk/RetrospectCalendar/View/RetrospectCalendarView.swift
Labels: 💡 Feature

#191 회고목록화면: 회고삭제에 대한 alert 기능
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/SortedRetrospects.swift
Labels: 💡 Feature

#198 엔티티 식별 리팩터링(#197)
  RetsTalk/NetworkTests/AssistantMessageProviderTest.swift
  RetsTalk/PersistTests/PersistTests.swift
  RetsTalk/PersistTests/TestEntity.swift
  RetsTalk/RetsTalk/Chat/Controller/RetrospectChatViewController.swift
  RetsTalk/RetsTalk/Chat/Model/Message.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
  RetsTalk/RetsTalk/Persistent/EntityRepresentable.swift
  RetsTalk/RetsTalk/Persistent/Implementation/CoreDataManager.swift
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
  RetsTalk/RetsTalk/Retrospect/Model/SortedRetrospects.swift
  RetsTalk/RetsTalk/RetrospectCalendar/Controller/RetrospectCalendarViewController.swift
  RetsTalk/RetsTalk/User/Model/UserData.swift
  RetsTalk/RetsTalk/Utility/View/BaseViewController.swift
  RetsTalk/RetsTalkTests/Mock/MockMessageStore.swift
  RetsTalk/RetsTalkTests/Mock/MockRetrospectStore.swift
Labels: 💪 Refactor

#194 회고목록화면: 총 회고 수 기능
  RetsTalk/RetsTalk/Persistent/Implementation/CoreDataManager.swift
  RetsTalk/RetsTalk/Persistent/Implementation/UserDefaultsManager.swift
  RetsTalk/RetsTalk/Persistent/Persistable.swift
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManageable.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalk/Retrospect/Model/SortedRetrospects.swift
  RetsTalk/RetsTalk/Retrospect/View/RetrospectCountButton.swift
  RetsTalk/RetsTalk/Retrospect/View/RetrospectListView.swift
Labels: 💡 Feature

#203 회고목록화면: 스크롤링을 통한 이전 회고 불러오기
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManageable.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
Labels: 💡 Feature

#205 UserSettingManager가 main-actor isolated 되도록 수정, Cloud 연동 로직을 delegate로 변경
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManageable.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalk/User/Controller/UserSettingViewController.swift
  RetsTalk/RetsTalk/User/Model/NotificationManageable.swift
  RetsTalk/RetsTalk/User/Model/NotificationManager.swift
  RetsTalk/RetsTalk/User/Model/UserSettingManageable.swift
  RetsTalk/RetsTalk/User/Model/UserSettingManager.swift
  RetsTalk/RetsTalk/User/UserSettingView.swift
  RetsTalk/RetsTalk/Utility/View/AlertPresentable.swift
  RetsTalk/RetsTalk/Utility/View/BaseHostingViewController.swift
Labels: 💪 Refactor

#206 회고목록화면: 진행 중인 회고에 대해 마지막 메세지를 셀에 보여주는 기능
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
Labels: 💡 Feature

#207 회고 대화 관리자 개선 및 뷰 연결(#144)
  RetsTalk/NetworkTests/AssistantMessageProviderTest.swift
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/App/SceneDelegate.swift
  RetsTalk/RetsTalk/Chat/Controller/RetrospectChatViewController.swift
  RetsTalk/RetsTalk/Chat/Model/AssistantMessageProvider.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManageable.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
  RetsTalk/RetsTalk/Network/CLOVAStudio/CLOVAStudioManager+AssistantMessageProvider.swift
  RetsTalk/RetsTalk/Persistent/Implementation/UserDefaultsManager.swift
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManageable.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalk/Utility/Enums/Constants.swift
  RetsTalk/RetsTalkTests/Mock/MockMessageStore.swift
  RetsTalk/RetsTalkTests/Mock/MockRetrospectAssistantProvider.swift
  RetsTalk/RetsTalkTests/Mock/MockRetrospectStore.swift
  RetsTalk/RetsTalkTests/RetrospectChatManagerTests.swift
  RetsTalk/RetsTalkTests/RetrospectManagerTests.swift
Labels: 💪 Refactor

#208 회고목록화면: 이달의 회고 수 기능
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManageable.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalk/Retrospect/View/RetrospectListView.swift
Labels: 💡 Feature

#210 회고목록화면을 구성하는 뷰 개선
  RetsTalk/RetsTalk/Retrospect/View/RetrospectListView.swift
  RetsTalk/RetsTalk/Retrospect/View/SectionHeaderView.swift
Labels: 💪 Refactor

#212 이전 회고 불러오기: 요청 오류 해결
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManageable.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalk/Retrospect/View/RetrospectListView.swift
Labels: 🛠️ Fix

#217 회고 도움 요청 표시 및 재시도 기능 추가(#93)
  RetsTalk/RetsTalk/Chat/Controller/RetrospectChatViewController.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
  RetsTalk/RetsTalk/Chat/View/ChatView.swift
  RetsTalk/RetsTalk/Chat/View/MessageInputView.swift
  RetsTalk/RetsTalk/Chat/View/RetryView.swift
  RetsTalk/RetsTalk/Network/NetworkRequestable.swift
Labels: 💡 Feature

#214 회고 캘린더를 Model과 연결해서 동작하도록 구현
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalk/RetrospectCalendar/Controller/RetrospectCalendarTableViewController.swift
  RetsTalk/RetsTalk/RetrospectCalendar/Controller/RetrospectCalendarViewController.swift
  RetsTalk/RetsTalk/RetrospectCalendar/View/RetrospectCalendarTableView.swift
  RetsTalk/RetsTalk/RetrospectCalendar/View/RetrospectCalendarView.swift
  RetsTalk/RetsTalk/Utility/Extensions/Date+Extension.swift
  RetsTalk/RetsTalk/Utility/Extensions/DateComponents+Extension.swift
Labels: 💡 Feature

#223 회고 대화 오류/끝내기 Alert 및 고정 기능(#218)
  RetsTalk/RetsTalk/Chat/Controller/RetrospectChatViewController.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
  RetsTalk/RetsTalk/Chat/View/ChatView.swift
  RetsTalk/RetsTalk/Chat/View/MessageInputView.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalk/Utility/Extensions/UIImage+Extension.swift
  RetsTalk/RetsTalk/Utility/View/AlertPresentable.swift
Labels: 💡 Feature

#224 대화 및 회고 프롬프트 개선
  RetsTalk/RetsTalk/Network/CLOVAStudio/CLOVAStudioAPI.swift
  RetsTalk/RetsTalk/Network/CLOVAStudio/CLOVAStudioManager+AssistantMessageProvider.swift
  RetsTalk/RetsTalk/Network/CLOVAStudio/CLOVAStudioManager+SummaryProvider.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
Labels: 💪 Refactor

#228 베이스 네비게이션 컨트롤러
  RetsTalk/RetsTalk/App/SceneDelegate.swift
  RetsTalk/RetsTalk/Utility/View/BaseNavigationController.swift
Labels: 💪 Refactor

#225 회고목록화면 리팩토링
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManageable.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
Labels: 💡 Feature, 💪 Refactor

#229 유저 설정 화면 색상 개선, iCloud state 확인 및 recordID 출력 기능 추가
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Persistent/CloudKitManageable.swift
  RetsTalk/RetsTalk/Persistent/Implementation/CloudKitManager.swift
  RetsTalk/RetsTalk/User/Controller/UserSettingViewController.swift
  RetsTalk/RetsTalk/User/Model/UserSettingManageable.swift
  RetsTalk/RetsTalk/User/Model/UserSettingManager.swift
  RetsTalk/RetsTalk/User/Subview/NicknameModalView.swift
  RetsTalk/RetsTalk/User/Subview/NicknameSettingView.swift
  RetsTalk/RetsTalk/User/UserSettingView.swift
Labels: 💡 Feature, 💪 Refactor

#230 버튼스타일, 회고셀 요약내용 변경
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/View/RetrospectCountButton.swift
  RetsTalk/RetsTalk/Retrospect/View/RetrospectListView.swift
Labels: 🎨 Style

#232 회고 매니저와 회고 캘린더 매니저 분리
  RetsTalk/.swiftlint.yml
  RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalk/RetrospectCalendar/Controller/RetrospectCalendarTableViewController.swift
  RetsTalk/RetsTalk/RetrospectCalendar/Controller/RetrospectCalendarViewController.swift
  RetsTalk/RetsTalk/RetrospectCalendar/Model/RetrospectCalendarManageable.swift
  RetsTalk/RetsTalk/RetrospectCalendar/Model/RetrospectCalendarManager.swift
  RetsTalk/RetsTalk/RetrospectCalendar/View/RetrospectCalendarView.swift
Labels: 💡 Feature

#239 UserID 고정, CloudKit 연결 시 셀에 중복된 회고가 보이는 문제 해결, 회고 프롬프트 수정
  RetsTalk/RetsTalk/App/SceneDelegate.swift
  RetsTalk/RetsTalk/Network/CLOVAStudio/CLOVAStudioManager+SummaryProvider.swift
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
  RetsTalk/RetsTalk/User/Model/UserSettingManageable.swift
  RetsTalk/RetsTalk/User/Model/UserSettingManager.swift
Labels: 🛠️ Fix, 💪 Refactor

#240 회고 업데이트시 테이블회고 캘린더에서 업데이트시 회고 캘린더와 List에 반영되도록 구현 뷰에 반영되도록 구현
  RetsTalk/.swiftlint.yml
  RetsTalk/RetsTalk/Chat/Controller/RetrospectChatViewController.swift
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalk/RetrospectCalendar/Controller/RetrospectCalendarTableViewController.swift
  RetsTalk/RetsTalk/RetrospectCalendar/Controller/RetrospectCalendarViewController.swift
Labels: 🛠️ Fix
