Repository boostcampwm-2024/iOS01-Ret-s-Talk, pull requests merged in 2024-11, with the labels that each got.

#6 Xcode 프로젝트 초기 세팅 및 Lint 설정
  .gitignore
  RetsTalk/.swiftlint.yml
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  RetsTalk/RetsTalk.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  RetsTalk/RetsTalk/App/AppDelegate.swift
  RetsTalk/RetsTalk/App/Base.lproj/LaunchScreen.storyboard
  RetsTalk/RetsTalk/App/SceneDelegate.swift
  RetsTalk/RetsTalk/Assets.xcassets/AccentColor.colorset/Contents.json
  RetsTalk/RetsTalk/Assets.xcassets/AppIcon.appiconset/Contents.json
  RetsTalk/RetsTalk/Assets.xcassets/Contents.json
  RetsTalk/RetsTalk/Info.plist
  RetsTalk/RetsTalk/RetsTalk.xcdatamodeld/.xccurrentversion
  RetsTalk/RetsTalk/RetsTalk.xcdatamodeld/RetsTalk.xcdatamodel/contents
  RetsTalk/RetsTalkTests/RetsTalkTests.swift
Labels: 💡 Feature

#13 네트워크 모듈 및 테스트
  .gitignore
  RetsTalk/NetworkTests/MockServerTests.swift
  RetsTalk/NetworkTests/MockURLProtocol.swift
  RetsTalk/NetworkTests/NetworkComposerTests.swift
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/App/AppDelegate.swift
  RetsTalk/RetsTalk/App/SceneDelegate.swift
  RetsTalk/RetsTalk/Network/CLOVAStudioAPI.swift
  RetsTalk/RetsTalk/Network/CLOVAStudioNetworkManager.swift
  RetsTalk/RetsTalk/Network/HTTPMethod.swift
  RetsTalk/RetsTalk/Network/NetworkError.swift
  RetsTalk/RetsTalk/Network/NetworkRequestable.swift
  RetsTalk/RetsTalk/Network/URLRequestComposable.swift
  RetsTalk/RetsTalk/Utility/Encodable+Extension.swift
Labels: 💡 Feature

#32 앱 아이콘 적용 및 ColorSet, FontSet 등 스타일 관련 초기 설정
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Assets.xcassets/AppIcon.appiconset/Contents.json
  RetsTalk/RetsTalk/Assets.xcassets/AppIcon.appiconset/RetsTalk-icon-dark.png
  RetsTalk/RetsTalk/Assets.xcassets/AppIcon.appiconset/RetsTalk-icon-white.jpeg
  RetsTalk/RetsTalk/Utility/Enums/ColorSet.swift
  RetsTalk/RetsTalk/Utility/Enums/FontSet.swift
  RetsTalk/RetsTalk/Utility/Extensions/Encodable+Extension.swift
  RetsTalk/RetsTalk/Utility/Extensions/UIColor+Extension.swift
  RetsTalk/RetsTalk/Utility/Extensions/UIFont+Extension.swift
Labels: 🎨 Style

#34 CoreData 사용을 위한 추상화 interface 구현
  RetsTalk/RetsTalk/Data/Persistent/CoreDataPersistable.swift
Labels: 💪 Refactor

#38 채팅 입력창 UI 및 세부 기능 구현
  RetsTalk/RetsTalk/Presentation/Chatting/Cell/AssistantMessageCell.swift
  RetsTalk/RetsTalk/Presentation/Chatting/Cell/UIHostingCell.swift
  RetsTalk/RetsTalk/Presentation/Chatting/Cell/UserMessageCell.swift
  RetsTalk/RetsTalk/Presentation/Chatting/ChatView.swift
  RetsTalk/RetsTalk/Presentation/Chatting/ChattingViewController.swift
  RetsTalk/RetsTalk/Presentation/Chatting/MessageInputView.swift
Labels: 💡 Feature

#37 채팅창 UI 부분에서 채팅 TableView 구성
  RetsTalk/RetsTalk/Data/Persistent/CoreDataStorage.swift
  RetsTalk/RetsTalk/Presentation/Chatting/Cell/AssistantMessageCell.swift
  RetsTalk/RetsTalk/Presentation/Chatting/Cell/MessageCell.swift
  RetsTalk/RetsTalk/Presentation/Chatting/Cell/UserMessageCell.swift
  RetsTalk/RetsTalk/Presentation/Chatting/ChatView.swift
  RetsTalk/RetsTalk/Presentation/Chatting/ChattingViewController.swift
  RetsTalk/RetsTalk/Presentation/Chatting/MessageInputView.swift
  RetsTalk/RetsTalk/Utility/Extensions/Color+Extension.swift
  RetsTalk/RetsTalk/Utility/Extensions/Font+Extension.swift
Labels: 💡 Feature

#42 Assets에 Color asset 추가
  RetsTalk/RetsTalk/App/AppDelegate.swift
  RetsTalk/RetsTalk/Assets.xcassets/BackgroundMain.colorset/Contents.json
  RetsTalk/RetsTalk/Assets.xcassets/BackgroundRetrospect.colorset/Contents.json
  RetsTalk/RetsTalk/Assets.xcassets/BlazingOrange.colorset/Contents.json
  RetsTalk/RetsTalk/Assets.xcassets/BlueBerry.colorset/Contents.json
  RetsTalk/RetsTalk/Assets.xcassets/StrokeRetrospect.colorset/Contents.json
  RetsTalk/RetsTalk/Info.plist
Labels: 🎨 Style

#46 프로젝트 구조 변경에 따른 폴더링 개선
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Chat/Controller/ChattingViewController.swift
  RetsTalk/RetsTalk/Chat/Model/Message.swift
  RetsTalk/RetsTalk/Chat/Model/MessageManageable.swift
  RetsTalk/RetsTalk/Chat/Model/MessageManagerListener.swift
  RetsTalk/RetsTalk/Chat/View/Cell/MessageCell.swift
  RetsTalk/RetsTalk/Chat/View/ChatView.swift
  RetsTalk/RetsTalk/Chat/View/MessageInputView.swift
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManageable.swift
  RetsTalk/RetsTalk/Retrospect/View/Cell/RetrospectCell.swift
  RetsTalk/RetsTalk/Retrospect/View/RetrospectView.swift
Labels: 💪 Refactor

#50 저장소 인터페이스 리팩터링#49
  RetsTalk/RetsTalk/Data/Persistent/CoreDataMessageStorage.swift
  RetsTalk/RetsTalk/Data/Persistent/CoreDataPersistable.swift
  RetsTalk/RetsTalk/Data/Persistent/CoreDataRetrospectStorage.swift
  RetsTalk/RetsTalk/Data/Persistent/MessageEntity+CoreDataClass.swift
  RetsTalk/RetsTalk/Data/Persistent/RetrospectEntity+CoreDataClass.swift
  RetsTalk/RetsTalk/Persistent/EntityRepresentable.swift
  RetsTalk/RetsTalk/Persistent/PersistFetchRequestable.swift
  RetsTalk/RetsTalk/Persistent/Persistable.swift
Labels: 💪 Refactor

#51 네트워크 오류에 대한 다시시도 버튼 구현
  RetsTalk/RetsTalk/Chat/View/RetryView.swift
Labels: 💡 Feature

#55 코어 데이터 저장소 구현체 추가(#36)
  RetsTalk/PersistTests/PersistTests.swift
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk.xctestplan
  RetsTalk/RetsTalk/App/SceneDelegate.swift
  RetsTalk/RetsTalk/Data/Persistent/CoreDataStorage.swift
  RetsTalk/RetsTalk/Persistent/Implementation/CoreDataManager.swift
  RetsTalk/RetsTalk/Utility/Extensions/Collection+Extension.swift
Labels: 💡 Feature

#58 채팅방의 네비게이션 바 UI 구현
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/App/SceneDelegate.swift
  RetsTalk/RetsTalk/Chat/Controller/ChattingViewController.swift
  RetsTalk/RetsTalk/Chat/View/RetryView.swift
  RetsTalk/RetsTalk/Utility/Extensions/UIImage+Extension.swift
Labels: 💡 Feature

#57 회고와,메시지 관리자 구현체 기본 구성하고 Delegate로 이어주기
  RetsTalk/RetsTalk/Chat/Model/MessageManager.swift
  RetsTalk/RetsTalk/Chat/Model/MessageManagerListener.swift
  RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManageable.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalk/User/Controller/UserViewController.swift
  RetsTalk/RetsTalk/User/Model/User.swift
Labels: 💡 Feature

#60 전송버튼 활성화 로직, 입력창 Placeholder 로직 재구성 및 키보드 내리기 기능
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Chat/Controller/ChattingViewController.swift
  RetsTalk/RetsTalk/Chat/View/MessageInputView.swift
Labels: 💡 Feature, 🛠️ Fix

#64 회고 도움 메시지 제공자 인터페이스 정의(#63)
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Chat/Model/AssistantMessageProvider.swift
Labels: 💡 Feature

#62 채팅 전송 관련 로직 구현
  RetsTalk/RetsTalk/Chat/Controller/ChattingViewController.swift
  RetsTalk/RetsTalk/Chat/Model/MockMessageManageable.swift
  RetsTalk/RetsTalk/Chat/Model/MockMessageManager.swift
  RetsTalk/RetsTalk/Chat/Model/MockMessageManagerListener.swift
  RetsTalk/RetsTalk/Chat/View/ChatView.swift
  RetsTalk/RetsTalk/Chat/View/MessageInputView.swift
Labels: 💡 Feature

#75 Assistant Message Provider 구현(#69)
  RetsTalk/NetworkTests/AssistantMessageProviderTest.swift
  RetsTalk/NetworkTests/MockServerTests.swift
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Chat/Model/AssistantMessageProvider.swift
  RetsTalk/RetsTalk/Chat/Model/Message.swift
  RetsTalk/RetsTalk/Network/CLOVAStudio/CLOVAStudioAPI.swift
  RetsTalk/RetsTalk/Network/CLOVAStudio/CLOVAStudioManager+AssistantMessageProvider.swift
  RetsTalk/RetsTalk/Network/CLOVAStudio/CLOVAStudioManager.swift
  RetsTalk/RetsTalk/Network/CLOVAStudio/CLOVAStudioSecret.swift
  RetsTalk/RetsTalk/Network/NetworkError.swift
Labels: 💡 Feature

#76 MessageManageable의 구체타입 구현(Fetch 부분)
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Chat/Model/Message.swift
  RetsTalk/RetsTalk/Chat/Model/MessageManager.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalk/User/Controller/UserViewController.swift
  RetsTalk/RetsTalkTests/MessageManagerTests.swift
  RetsTalk/RetsTalkTests/MockMessageStore.swift
  RetsTalk/RetsTalkTests/MockRetrospectManager.swift
Labels: 💡 Feature

#74 회고 목록 화면: 셀, 테이블뷰 UI 구현
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectViewController.swift
  RetsTalk/RetsTalk/Retrospect/View/Cell/RetrospectCell.swift
  RetsTalk/RetsTalk/Retrospect/View/RetrospectView.swift
  RetsTalk/RetsTalk/Utility/Enums/Constants.swift
  RetsTalk/RetsTalk/Utility/Extensions/Date+Extension.swift
  RetsTalk/RetsTalk/Utility/Extensions/String+Extension.swift
Labels: 💡 Feature

#81 프로젝트 정상화(린트, 네이밍, 타겟)
  RetsTalk/.swiftlint.yml
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Network/CLOVAStudio/CLOVAStudioAPI.swift
  RetsTalk/RetsTalk/Network/CLOVAStudio/CLOVAStudioManager+AssistantMessageProvider.swift
  RetsTalk/RetsTalk/Network/CLOVAStudio/CLOVAStudioSecret.swift
  RetsTalk/RetsTalk/Retrospect/View/Cell/RetrospectCell.swift
Labels: 💪 Refactor

#78 메시지 관리자 인터페이스 업데이트에 따른 코드 리팩토링 & 전송 버튼 상태 관리 로직 추가
  RetsTalk/RetsTalk/Chat/Controller/ChattingViewController.swift
  RetsTalk/RetsTalk/Chat/Model/MockMessageManageable.swift
  RetsTalk/RetsTalk/Chat/Model/MockMessageManager.swift
  RetsTalk/RetsTalk/Chat/View/ChatView.swift
  RetsTalk/RetsTalk/Chat/View/MessageInputView.swift
  RetsTalk/RetsTalk/Utility/Extensions/String+Extension.swift
Labels: 💪 Refactor

#86 회고 생성 플로팅 버튼 UI 구현
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/View/CreateRetrospectButton.swift
  RetsTalk/RetsTalk/Retrospect/View/RetrospectListView.swift
  RetsTalk/RetsTalk/Utility/Enums/FontSet.swift
  RetsTalk/RetsTalk/Utility/Extensions/UIFont+Extension.swift
Labels: 💡 Feature

#99 CoreData Entity 수정, Model 변경, Manger 수정
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Chat/Model/Message.swift
  RetsTalk/RetsTalk/Chat/Model/MessageManagerListener.swift
  RetsTalk/RetsTalk/Chat/Model/MockMessageManager.swift
  RetsTalk/RetsTalk/Chat/Model/MockMessageManagerListener.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManageable.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManagerListener.swift
  RetsTalk/RetsTalk/Network/CLOVAStudio/CLOVAStudioManager+AssistantMessageProvider.swift
  RetsTalk/RetsTalk/Network/CLOVAStudio/CLOVAStudioManager+SummaryProvider.swift
  RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManageable.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalk/RetsTalk.xcdatamodeld/RetsTalk.xcdatamodel/contents
Labels: 💪 Refactor

#97 메세지셀, 챗뷰 Assets Color 적용 리팩토링
  RetsTalk/RetsTalk/Chat/View/Cell/MessageCell.swift
  RetsTalk/RetsTalk/Chat/View/ChatView.swift
  RetsTalk/RetsTalk/Chat/View/MessageInputView.swift
  RetsTalk/RetsTalk/Utility/Extensions/Color+Extension.swift
  RetsTalk/RetsTalk/Utility/Extensions/UIColor+Extension.swift
Labels: 💪 Refactor

#106 Develop 브랜치 빌드 되도록 수정
  RetsTalk/NetworkTests/AssistantMessageProviderTest.swift
  RetsTalk/NetworkTests/SummaryProviderTest.swift
  RetsTalk/RetsTalk/App/AppDelegate.swift
  RetsTalk/RetsTalk/Chat/Controller/ChattingViewController.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManageable.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalkTests/MessageManagerTests.swift
  RetsTalk/RetsTalkTests/Mock/MockAssistantMessageProvider.swift
  RetsTalk/RetsTalkTests/Mock/MockRetrospectManager.swift
Labels: 💪 Refactor

#101 회고 Manger 구현체 Fetch 구현
  RetsTalk/NetworkTests/MockServerTests.swift
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManageable.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalkTests/Mock/MockRetrospectManager.swift
  RetsTalk/RetsTalkTests/Mock/MockRetrospectStore.swift
  RetsTalk/RetsTalkTests/RetrospectChatManagerTests.swift
  RetsTalk/RetsTalkTests/RetrospectManagerTests.swift
Labels: 💡 Feature

#104 사용자 설정 화면 UI 구현
  RetsTalk/RetsTalk/User/UserSettingView.swift
Labels: 💡 Feature

#114 로컬 저장소 레이어 행위자(actor) 격리(#113)
  RetsTalk/PersistTests/PersistTests.swift
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
  RetsTalk/RetsTalk/Persistent/Implementation/CoreDataManager.swift
  RetsTalk/RetsTalk/Persistent/Implementation/PersistFetchRequest.swift
  RetsTalk/RetsTalk/Persistent/PersistFetchRequestable.swift
  RetsTalk/RetsTalk/Persistent/Persistable.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalkTests/Mock/MockMessageStore.swift
  RetsTalk/RetsTalkTests/Mock/MockRetrospectStore.swift
Labels: 💪 Refactor

#109 회고 매니저 Create 구현
  RetsTalk/RetsTalk/Chat/Controller/ChattingViewController.swift
  RetsTalk/RetsTalk/Chat/Model/Message.swift
  RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManageable.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalk/Retrospect/View/Cell/RetrospectCell.swift
  RetsTalk/RetsTalkTests/Mock/MockRetrospectStore.swift
  RetsTalk/RetsTalkTests/RetrospectManagerTests.swift
Labels: 💡 Feature

#117 UserDefaults 관리를 위한 매니저의 구현체 및 UserData 엔티티
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Persistent/Implementation/UserDefaultsManager.swift
  RetsTalk/RetsTalk/User/Model/UserData.swift
Labels: 💡 Feature

#122 회고 대화 로직 데이터 격리(#108)
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Chat/Controller/ChattingViewController.swift
  RetsTalk/RetsTalk/Chat/Model/Message.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManageable.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManagerListener.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalkTests/Mock/MockAssistantMessageProvider.swift
  RetsTalk/RetsTalkTests/Mock/MockMessageStore.swift
  RetsTalk/RetsTalkTests/Mock/MockRetrospectManager.swift
  RetsTalk/RetsTalkTests/RetrospectChatManagerTests.swift
Labels: 💪 Refactor

#124 사용자 설정 화면 모델 연결 및 닉네임 변경 구현
  RetsTalk/RetsTalk/User/Controller/UserSettingViewController.swift
  RetsTalk/RetsTalk/User/Model/UserSettingManageable.swift
  RetsTalk/RetsTalk/User/Model/UserSettingManager.swift
  RetsTalk/RetsTalk/User/Subview/AppVersionView.swift
  RetsTalk/RetsTalk/User/Subview/CloudSettingView.swift
  RetsTalk/RetsTalk/User/Subview/NicknameModalView.swift
  RetsTalk/RetsTalk/User/Subview/NicknameSettingView.swift
  RetsTalk/RetsTalk/User/Subview/NotificationSettingView.swift
  RetsTalk/RetsTalk/User/UserSettingView.swift
Labels: 💡 Feature

#131 뷰 컨트롤러 계층화
  RetsTalk/RetsTalk/Utility/View/AlertPresentable.swift
  RetsTalk/RetsTalk/Utility/View/BaseKeyBoardViewController.swift
  RetsTalk/RetsTalk/Utility/View/BaseViewController.swift
Labels: 💪 Refactor

#137 CoreDataManager: init 메서드의 Sendable 핸들러 전달
  RetsTalk/RetsTalk/Persistent/Implementation/CoreDataManager.swift
Labels: 🛠️ Fix

#138 RetospectManageable: 존재하는 회고를 열람하는 기능
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManageable.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
Labels: 💡 Feature

#140 RetrospectManager 회고고정 토글기능 오류 수정
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
Labels: 🛠️ Fix

#141 채팅 prepend 기능 추가
  RetsTalk/RetsTalk/Chat/Controller/ChattingViewController.swift
  RetsTalk/RetsTalk/Chat/Controller/RetrospectChatViewController.swift
  RetsTalk/RetsTalk/Chat/Model/Message.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
  RetsTalk/RetsTalk/Chat/View/ChatView.swift
Labels: 💡 Feature

#132 회고 목록 화면 임시모델 연결 및 추가기능 연결
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/MockRetrospectManager.swift
  RetsTalk/RetsTalk/Retrospect/View/Cell/RetrospectCell.swift
  RetsTalk/RetsTalk/Retrospect/View/RetrospectListView.swift
  RetsTalk/RetsTalk/User/Controller/UserSettingViewController.swift
  RetsTalk/RetsTalk/Utility/Enums/FontSet.swift
  RetsTalk/RetsTalk/Utility/Extensions/UIContextualAction+Extension.swift
  RetsTalk/RetsTalk/Utility/Extensions/UIImage+Extension.swift
  RetsTalk/RetsTalk/Utility/RetrospectSortingHelper.swift
Labels: 💡 Feature, 🛠️ Fix

#143 메시지 입력 높이 초기화 (#142)
  RetsTalk/RetsTalk/Chat/View/MessageInputView.swift
Labels: 🛠️ Fix

#139 CloudKit을 통해 CoreData와 iCloud 데이터를 동기화할 수 있도록 CoreDataManager 변경
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/Info.plist
  RetsTalk/RetsTalk/Persistent/Implementation/CoreDataManager.swift
  RetsTalk/RetsTalk/Retrospect/Model/Retrospect.swift
  RetsTalk/RetsTalk/RetsTalk.entitlements
  RetsTalk/RetsTalk/RetsTalk.xcdatamodeld/RetsTalk.xcdatamodel/contents
  RetsTalk/RetsTalk/Utility/Extensions/NotificationName+Extension.swift
Labels: 💡 Feature

#158 빌드 에러나는 부분 수정
  RetsTalk/RetsTalk.xcodeproj/project.pbxproj
  RetsTalk/RetsTalk/App/SceneDelegate.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManageable.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManager.swift
  RetsTalk/RetsTalk/Chat/Model/RetrospectChatManagerListener.swift
  RetsTalk/RetsTalk/Retrospect/Controller/RetrospectListViewController.swift
  RetsTalk/RetsTalk/Retrospect/Model/MockRetrospectManager.swift
  RetsTalk/RetsTalk/Retrospect/Model/RetrospectManager.swift
  RetsTalk/RetsTalk/Utility/View/BaseViewController.swift
  RetsTalk/RetsTalkTests/Mock/MockTestRetrospectManager.swift
  RetsTalk/RetsTalkTests/RetrospectChatManagerTests.swift
Labels: 🛠️ Fix

#149 클라우드 동기화 on/off 기능
  RetsTalk/RetsTalk/User/Model/UserSettingManager.swift
  RetsTalk/RetsTalk/User/Subview/CloudSettingView.swift
  RetsTalk/RetsTalk/User/UserSettingView.swift
Labels: 💡 Feature

#155 사용자 설정화면: 레이블 추가 및 색상, 버튼 크기 조정
  RetsTalk/RetsTalk/User/Subview/NicknameModalView.swift
  RetsTalk/RetsTalk/User/Subview/NicknameSettingView.swift
Labels: 🎨 Style

#157 온보딩 화면 UI
  RetsTalk/RetsTalk/OnBoarding/OnBoardingView.swift
Labels: 💡 Feature
